name: Plugins Release

on:
  release:
    types: [released]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Parse checksum
        id: parse_checksum
        run: echo "checksum=$(grep -o '[a-fA-F0-9]\{64\}' Package.swift)" >> $GITHUB_OUTPUT
      - name: Dispatch release of plugins package
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.SIMPLYDANNY_PLUGINS_SYNC }}
          repository: SimplyDanny/SwiftLintPlugins
          event-type: swiftlint-release
          client-payload: |-
            {
              "title": "${{ github.event.release.name }}",
              "tag": "${{ github.ref_name }}",
              "checksum": "${{ steps.parse_checksum.outputs.checksum }}"
            }
